"""Update PieceEditLogReport.

Revision ID: 46baa7945dbd
Revises: 281ba0430ae5
Create Date: 2015-04-11 20:08:19.356010

"""

# revision identifiers, used by Alembic.
revision = '46baa7945dbd'
down_revision = '281ba0430ae5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece_edit_log_report', sa.Column('log_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'piece_edit_log_report_ibfk_3', 'piece_edit_log_report', type_='foreignkey')
    op.create_foreign_key(None, 'piece_edit_log_report', 'piece_edit_log', ['log_id'], ['id'])
    op.drop_column('piece_edit_log_report', 'piece_edit_log_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece_edit_log_report', sa.Column('piece_edit_log_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'piece_edit_log_report', type_='foreignkey')
    op.create_foreign_key(u'piece_edit_log_report_ibfk_3', 'piece_edit_log_report', 'piece_edit_log', ['piece_edit_log_id'], ['id'])
    op.drop_column('piece_edit_log_report', 'log_id')
    ### end Alembic commands ###
