"""Update user

Revision ID: 4c335d302ebb
Revises: 577cf6d0fed9
Create Date: 2015-03-19 19:07:44.969041

"""

# revision identifiers, used by Alembic.
revision = '4c335d302ebb'
down_revision = '577cf6d0fed9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('collections_count', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('pieces_count', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('votes_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'votes_count')
    op.drop_column('user', 'pieces_count')
    op.drop_column('user', 'collections_count')
    ### end Alembic commands ###
