"""Add PieceVote, PieceComment, PieceCommentLike.

Revision ID: 26ac19fecf2f
Revises: 4c68cd7700d4
Create Date: 2015-03-07 15:31:08.277317

"""

# revision identifiers, used by Alembic.
revision = '26ac19fecf2f'
down_revision = '4c68cd7700d4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piece_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('piece_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('piece_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('piece_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('piece_comment_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('piece_comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['piece_comment_id'], ['piece_comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'piece', sa.Column('clicks_count', sa.Integer(), nullable=True))
    op.add_column(u'piece', sa.Column('page', sa.Integer(), nullable=True))
    op.add_column(u'piece', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column(u'piece', sa.Column('source_url', sa.String(length=200), nullable=True))
    op.add_column(u'piece', sa.Column('votes_count', sa.Integer(), nullable=True))
    op.drop_column(u'piece', 'page_start')
    op.drop_column(u'piece', 'page_end')
    op.drop_column(u'piece', 'review')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'piece', sa.Column('review', mysql.TEXT(), nullable=True))
    op.add_column(u'piece', sa.Column('page_end', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column(u'piece', sa.Column('page_start', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column(u'piece', 'votes_count')
    op.drop_column(u'piece', 'source_url')
    op.drop_column(u'piece', 'source')
    op.drop_column(u'piece', 'page')
    op.drop_column(u'piece', 'clicks_count')
    op.drop_constraint(None, 'book', type_='unique')
    op.drop_table('piece_comment_like')
    op.drop_table('piece_comment')
    op.drop_table('piece_vote')
    ### end Alembic commands ###
