"""Update Piece Edit Log.

Revision ID: f731dfb9ee8
Revises: 327f7652a2dc
Create Date: 2015-04-07 17:54:55.406709

"""

# revision identifiers, used by Alembic.
revision = 'f731dfb9ee8'
down_revision = '327f7652a2dc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece_edit_log', sa.Column('after', sa.String(length=200), nullable=True))
    op.add_column('piece_edit_log', sa.Column('after_id', sa.Integer(), nullable=True))
    op.add_column('piece_edit_log', sa.Column('before', sa.String(length=200), nullable=True))
    op.add_column('piece_edit_log', sa.Column('before_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'piece_edit_log_ibfk_1', 'piece_edit_log', type_='foreignkey')
    op.drop_column('piece_edit_log', 'collection_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece_edit_log', sa.Column('collection_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'piece_edit_log_ibfk_1', 'piece_edit_log', 'collection', ['collection_id'], ['id'])
    op.drop_column('piece_edit_log', 'before_id')
    op.drop_column('piece_edit_log', 'before')
    op.drop_column('piece_edit_log', 'after_id')
    op.drop_column('piece_edit_log', 'after')
    ### end Alembic commands ###
