"""Add original to piece.

Revision ID: 465b75670e5
Revises: 33c53247fc0b
Create Date: 2015-03-12 12:21:38.773420

"""

# revision identifiers, used by Alembic.
revision = '465b75670e5'
down_revision = '33c53247fc0b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('original', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('piece', 'original')
    ### end Alembic commands ###
