"""Add InvitationCode.

Revision ID: 18ecb8911284
Revises: 51a5b92bb7d6
Create Date: 2015-04-10 15:55:10.776425

"""

# revision identifiers, used by Alembic.
revision = '18ecb8911284'
down_revision = '51a5b92bb7d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('sended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitation_code')
    ### end Alembic commands ###
