"""Update db.

Revision ID: 4c68cd7700d4
Revises: None
Create Date: 2015-03-07 11:03:03.067082

"""

# revision identifiers, used by Alembic.
revision = '4c68cd7700d4'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('excerpt')
    op.create_table('piece',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excerpt',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('review', mysql.TEXT(), nullable=True),
    sa.Column('page_start', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('page_end', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('create_time', sa.DATE(), nullable=True),
    sa.Column('book_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'MyISAM'
    )
    op.drop_table('piece')
    op.drop_table('user')
    ### end Alembic commands ###
