"""Add book

Revision ID: 2be1615e9237
Revises: 33c53247fc0b
Create Date: 2015-03-11 23:52:10.709120

"""

# revision identifiers, used by Alembic.
revision = '2be1615e9237'
down_revision = '33c53247fc0b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('intro', sa.Text(), nullable=True),
    sa.Column('cover', sa.String(length=200), nullable=True),
    sa.Column('amazon_url', sa.String(length=300), nullable=True),
    sa.Column('douban_url', sa.String(length=200), nullable=True),
    sa.Column('pub_date', sa.Date(), nullable=True),
    sa.Column('press', sa.String(length=100), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('isbn', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'piece', sa.Column('book_id', sa.Integer(), nullable=True))
    op.add_column(u'piece', sa.Column('page', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'piece', 'book', ['book_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'piece', type_='foreignkey')
    op.drop_column(u'piece', 'page')
    op.drop_column(u'piece', 'book_id')
    op.drop_table('book')
    ### end Alembic commands ###
