"""Add PieceEditLog model.

Revision ID: 1f1d40709240
Revises: 27f23fe2cac4
Create Date: 2015-03-28 10:56:48.188979

"""

# revision identifiers, used by Alembic.
revision = '1f1d40709240'
down_revision = '27f23fe2cac4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piece_edit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('piece_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'collection', 'sm_cover')
    op.drop_constraint(u'collection_piece_ibfk_3', 'collection_piece', type_='foreignkey')
    op.drop_column(u'collection_piece', 'user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'collection_piece', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'collection_piece_ibfk_3', 'collection_piece', 'user', ['user_id'], ['id'])
    op.add_column(u'collection', sa.Column('sm_cover', mysql.VARCHAR(length=200), nullable=True))
    op.drop_table('piece_edit_log')
    ### end Alembic commands ###
