"""Update user.

Revision ID: 60d61fb9582
Revises: 538b8864e5a9
Create Date: 2015-04-01 21:42:50.917321

"""

# revision identifiers, used by Alembic.
revision = '60d61fb9582'
down_revision = '538b8864e5a9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('liked_collections_count', sa.Integer(), nullable=True))
    op.drop_column('user', 'collections_count')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('collections_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('user', 'liked_collections_count')
    ### end Alembic commands ###
