"""Add target_user_id to PieceComment.

Revision ID: 2c91d039aba3
Revises: 21617647835f
Create Date: 2015-04-02 16:03:55.178323

"""

# revision identifiers, used by Alembic.
revision = '2c91d039aba3'
down_revision = '21617647835f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece_comment', sa.Column('target_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'piece_comment', 'user', ['target_user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'piece_comment', type_='foreignkey')
    op.drop_column('piece_comment', 'target_user_id')
    ### end Alembic commands ###
