"""Add notification model.

Revision ID: 39a3ac4b11ab
Revises: 2c91d039aba3
Create Date: 2015-04-04 18:55:11.822111

"""

# revision identifiers, used by Alembic.
revision = '39a3ac4b11ab'
down_revision = '2c91d039aba3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
