"""Add CollectionEditLog models

Revision ID: f94e45ac2bd
Revises: 4f6efd51742d
Create Date: 2015-04-09 10:48:24.390636

"""

# revision identifiers, used by Alembic.
revision = 'f94e45ac2bd'
down_revision = '4f6efd51742d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_edit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('kind', sa.Integer(), nullable=False),
    sa.Column('before', sa.String(length=200), nullable=True),
    sa.Column('before_id', sa.Integer(), nullable=True),
    sa.Column('after', sa.String(length=200), nullable=True),
    sa.Column('after_id', sa.Integer(), nullable=True),
    sa.Column('compare', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_edit_log_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('collection_edit_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_edit_log_id'], ['collection_edit_log.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'piece_edit_log_report', 'piece_edit_log', ['piece_edit_log_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'piece_edit_log_report', type_='foreignkey')
    op.drop_table('collection_edit_log_report')
    op.drop_table('collection_edit_log')
    ### end Alembic commands ###
