"""Add user to piece.

Revision ID: 56e170bc2a8f
Revises: 42743fd63f51
Create Date: 2015-03-07 23:46:24.586889

"""

# revision identifiers, used by Alembic.
revision = '56e170bc2a8f'
down_revision = '42743fd63f51'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'piece', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'piece', type_='foreignkey')
    op.drop_column('piece', 'user_id')
    ### end Alembic commands ###
