"""Update PieceEditLog.

Revision ID: 319e8e7d746a
Revises: 490fa40df32d
Create Date: 2015-04-08 09:12:11.089265

"""

# revision identifiers, used by Alembic.
revision = '319e8e7d746a'
down_revision = '490fa40df32d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece_edit_log', sa.Column('after', sa.String(length=200), nullable=True))
    op.add_column('piece_edit_log', sa.Column('after_id', sa.Integer(), nullable=True))
    op.add_column('piece_edit_log', sa.Column('before', sa.String(length=200), nullable=True))
    op.add_column('piece_edit_log', sa.Column('before_id', sa.Integer(), nullable=True))
    op.add_column('piece_edit_log', sa.Column('compare', sa.String(length=500), nullable=True))
    op.drop_column('piece_edit_log', 'result_id')
    op.drop_column('piece_edit_log', 'result')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece_edit_log', sa.Column('result', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('piece_edit_log', sa.Column('result_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('piece_edit_log', 'compare')
    op.drop_column('piece_edit_log', 'before_id')
    op.drop_column('piece_edit_log', 'before')
    op.drop_column('piece_edit_log', 'after_id')
    op.drop_column('piece_edit_log', 'after')
    ### end Alembic commands ###
