"""Add content length to Piece modal.

Revision ID: 49086f55444e
Revises: 11fc5ea9e16a
Create Date: 2015-04-21 18:30:17.163304

"""

# revision identifiers, used by Alembic.
revision = '49086f55444e'
down_revision = '11fc5ea9e16a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('content_length', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('piece', 'content_length')
    ### end Alembic commands ###
