"""Add processed to PieceEditLogReport.

Revision ID: 281ba0430ae5
Revises: 505e944a76a9
Create Date: 2015-04-11 20:02:57.867776

"""

# revision identifiers, used by Alembic.
revision = '281ba0430ae5'
down_revision = '505e944a76a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece_edit_log_report', sa.Column('processed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('piece_edit_log_report', 'processed')
    ### end Alembic commands ###
