"""Rm book

Revision ID: 30a392ef4eba
Revises: 56e170bc2a8f
Create Date: 2015-03-10 19:49:07.798270

"""

# revision identifiers, used by Alembic.
revision = '30a392ef4eba'
down_revision = '56e170bc2a8f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'piece_ibfk_1', 'piece', type_='foreignkey')
    op.drop_column('piece', 'page')
    op.drop_column('piece', 'book_id')
    op.drop_table('book')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('book_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('piece', sa.Column('page', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'piece_ibfk_1', 'piece', 'book', ['book_id'], ['id'])
    op.create_table('book',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('author', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('intro', mysql.TEXT(), nullable=True),
    sa.Column('cover_image', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('amazon_url', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('douban_url', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('pub_date', sa.DATE(), nullable=True),
    sa.Column('press', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('pages_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('price', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('isbn', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
