"""Add locked to collection model.

Revision ID: 567e157a313a
Revises: f94e45ac2bd
Create Date: 2015-04-09 11:03:42.683247

"""

# revision identifiers, used by Alembic.
revision = '567e157a313a'
down_revision = 'f94e45ac2bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('locked', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'locked')
    ### end Alembic commands ###
