"""Update PieceEditLog model.

Revision ID: 12e707edf972
Revises: 1f1d40709240
Create Date: 2015-03-28 11:24:25.836043

"""

# revision identifiers, used by Alembic.
revision = '12e707edf972'
down_revision = '1f1d40709240'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece_edit_log', sa.Column('kind', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('piece_edit_log', 'kind')
    ### end Alembic commands ###
