"""Update CollectionEditLogReport.

Revision ID: 4b9970e8b566
Revises: 283743d71843
Create Date: 2015-04-11 17:26:11.426929

"""

# revision identifiers, used by Alembic.
revision = '4b9970e8b566'
down_revision = '283743d71843'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_edit_log_report', sa.Column('log_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'collection_edit_log_report_ibfk_1', 'collection_edit_log_report', type_='foreignkey')
    op.create_foreign_key(None, 'collection_edit_log_report', 'collection_edit_log', ['log_id'], ['id'])
    op.drop_column('collection_edit_log_report', 'collection_edit_log_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_edit_log_report', sa.Column('collection_edit_log_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'collection_edit_log_report', type_='foreignkey')
    op.create_foreign_key(u'collection_edit_log_report_ibfk_1', 'collection_edit_log_report', 'collection_edit_log', ['collection_edit_log_id'], ['id'])
    op.drop_column('collection_edit_log_report', 'log_id')
    ### end Alembic commands ###
