"""Add is_active to User model.

Revision ID: d2b71fa7e5a
Revises: 200894a65290
Create Date: 2015-04-10 17:05:54.636774

"""

# revision identifiers, used by Alembic.
revision = 'd2b71fa7e5a'
down_revision = '200894a65290'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    ### end Alembic commands ###
