"""Update collection models

Revision ID: 32109a6277f7
Revises: 32772872fc66
Create Date: 2015-03-25 17:11:49.714304

"""

# revision identifiers, used by Alembic.
revision = '32109a6277f7'
down_revision = '32772872fc66'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'collection_ibfk_1', 'collection', type_='foreignkey')
    op.drop_column('collection', 'user_id')
    op.add_column('collection_piece', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'collection_piece_ibfk_3', 'collection_piece', type_='foreignkey')
    op.create_foreign_key(None, 'collection_piece', 'user', ['user_id'], ['id'])
    op.drop_column('collection_piece', 'collection_owner_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_piece', sa.Column('collection_owner_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'collection_piece', type_='foreignkey')
    op.create_foreign_key(u'collection_piece_ibfk_3', 'collection_piece', 'user', ['collection_owner_id'], ['id'])
    op.drop_column('collection_piece', 'user_id')
    op.add_column('collection', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'collection_ibfk_1', 'collection', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###
