"""Update piece.

Revision ID: 38e41625bbba
Revises: 2be1615e9237
Create Date: 2015-03-11 23:57:32.149265

"""

# revision identifiers, used by Alembic.
revision = '38e41625bbba'
down_revision = '2be1615e9237'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('piece', 'source')
    op.drop_column('piece', 'source_url')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('source_url', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('piece', sa.Column('source', mysql.VARCHAR(length=100), nullable=True))
    ### end Alembic commands ###
