"""Update Piece Edit Log.

Revision ID: 490fa40df32d
Revises: f731dfb9ee8
Create Date: 2015-04-07 19:55:58.223758

"""

# revision identifiers, used by Alembic.
revision = '490fa40df32d'
down_revision = 'f731dfb9ee8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece_edit_log', sa.Column('result', sa.String(length=200), nullable=True))
    op.add_column('piece_edit_log', sa.Column('result_id', sa.Integer(), nullable=True))
    op.drop_column('piece_edit_log', 'before_id')
    op.drop_column('piece_edit_log', 'after')
    op.drop_column('piece_edit_log', 'after_id')
    op.drop_column('piece_edit_log', 'before')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece_edit_log', sa.Column('before', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('piece_edit_log', sa.Column('after_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('piece_edit_log', sa.Column('after', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('piece_edit_log', sa.Column('before_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('piece_edit_log', 'result_id')
    op.drop_column('piece_edit_log', 'result')
    ### end Alembic commands ###
