"""Update user

Revision ID: 33c53247fc0b
Revises: 30a392ef4eba
Create Date: 2015-03-11 00:14:55.659227

"""

# revision identifiers, used by Alembic.
revision = '33c53247fc0b'
down_revision = '30a392ef4eba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('blog', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('douban', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('motto', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('weibo', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('zhihu', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'zhihu')
    op.drop_column('user', 'weibo')
    op.drop_column('user', 'motto')
    op.drop_column('user', 'douban')
    op.drop_column('user', 'blog')
    ### end Alembic commands ###
