"""Update PieceCommentVote.

Revision ID: 35c0d4e5f47
Revises: 60d61fb9582
Create Date: 2015-04-02 10:37:19.831205

"""

# revision identifiers, used by Alembic.
revision = '35c0d4e5f47'
down_revision = '60d61fb9582'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piece_comment_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('piece_comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['piece_comment_id'], ['piece_comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('piece_comment_like')
    op.add_column('piece_comment', sa.Column('votes_count', sa.Integer(), nullable=True))
    op.drop_column('piece_comment', 'likes_count')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece_comment', sa.Column('likes_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('piece_comment', 'votes_count')
    op.create_table('piece_comment_like',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('piece_comment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['piece_comment_id'], [u'piece_comment.id'], name=u'piece_comment_like_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'piece_comment_like_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('piece_comment_vote')
    ### end Alembic commands ###
