"""Update piece.

Revision ID: 32772872fc66
Revises: 3fce78804aa2
Create Date: 2015-03-21 15:21:58.356130

"""

# revision identifiers, used by Alembic.
revision = '32772872fc66'
down_revision = '3fce78804aa2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('source_link', sa.String(length=200), nullable=True))
    op.add_column('piece', sa.Column('source_link_title', sa.String(length=200), nullable=True))
    op.drop_column('piece', 'source_url')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('source_url', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('piece', 'source_link_title')
    op.drop_column('piece', 'source_link')
    ### end Alembic commands ###
