"""Add collection_owner_id to CollectionPiece

Revision ID: 577cf6d0fed9
Revises: 5a0ac4b48d58
Create Date: 2015-03-13 21:26:46.901269

"""

# revision identifiers, used by Alembic.
revision = '577cf6d0fed9'
down_revision = '5a0ac4b48d58'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_piece', sa.Column('collection_owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'collection_piece', 'user', ['collection_owner_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collection_piece', type_='foreignkey')
    op.drop_column('collection_piece', 'collection_owner_id')
    ### end Alembic commands ###
