"""Rename user like collection

Revision ID: 283743d71843
Revises: d2b71fa7e5a
Create Date: 2015-04-11 15:44:52.922475

"""

# revision identifiers, used by Alembic.
revision = '283743d71843'
down_revision = 'd2b71fa7e5a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user_like_collection', 'collection_like')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
        op.rename_table('collection_like', 'user_like_collection')
    ### end Alembic commands ###
