"""Update CollectionKind.

Revision ID: 9b2b4d0abcc
Revises: 46baa7945dbd
Create Date: 2015-04-12 00:53:01.690150

"""

# revision identifiers, used by Alembic.
revision = '9b2b4d0abcc'
down_revision = '46baa7945dbd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_kind', sa.Column('show_order', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_kind', 'show_order')
    ### end Alembic commands ###
